### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ENTERspaceAspaceUSERNAME** [Robin-Sch/robinsch-miner#2]
1. Does this require admnistrator rights?
2. Does this get detected byt Windows Defender?

**Comment by Robin-Sch** [comment]
1. It does not require admin rights, however, you will receive more performance with admin privileges.
2. It shouldn't be detected by windows defender, but you can always "allow threat" under the defender settings. If you try to start it and you receive an error like "windows has protected your pc" click the small text (I'm not sure what it says) and you can start it then. If you press the "normal" button it will close the application.

**Comment by ENTERspaceAspaceUSERNAME** [comment]
Does it run straight away when I run the exe for Windows?

**Comment by Robin-Sch** [comment]
You need to press the start cpu or start gpu button (or both).

**Comment by miracuves** [comment]
its not connecting to pool for now, if you have any solution for the same please let me know.

**Comment by Robin-Sch** [comment]
Is this your first time using it? If so, it's probably blocked by your DNS provider, please google "how to change my DNS server" and set it to 1.1.1.1 (cloudflare).
Try to go to https://moneroocean.stream/, if it shows an error this means your DNS provider is blocking it and you must change your DNS server to something like cloudflare.

If you've used it before (and it was working), it probably means that moneroocean is down. Please try again in a few hours.

**Comment by miracuves** [comment]
https://moneroocean.stream
this is working fine bro.
